name: PR Automation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Unit Tests
        run: |
          docker run --rm my-app pytest tests/

      - name: Code Scanning (Optional)
        uses: github/codeql-action/analyze@v2
        with:
          languages: 'javascript,python'

      - name: Post Check Comment
        if: success()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Build and tests passed. Ready for review."

  merge:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Auto Merge PR
        uses: actions-ecosystem/action-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
