name: PR Automation with Docker, Tests, Slack, and Approval

on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t sample-nodejs-app .

      - name: Run Tests
        run: docker run --rm sample-nodejs-app npm test

  codeql:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Build the code
        run: npm install

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results/codeql-results.sarif

      - name: Create Results Directory
        run: mkdir -p results

      - name: CheckIfCodeQLOutputExists
        run: ls -R results || echo "No CodeQL results found."

      - name: Upload XML report to Slack
        if: ${{ success() && steps.CheckIfCodeQLOutputExists.outcome == 'success' }}
        run: |
          curl -F file=@results/codeql-results.sarif -F "initial_comment=CodeQL SARIF Report" \
          -F channels=${{ secrets.SLACK_CHANNEL }} \
          -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" https://slack.com/api/files.upload

  approval:
    runs-on: ubuntu-latest
    needs: codeql
    if: ${{ success() }}

    steps:
      - name: Request Approval
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MERGE_METHOD: 'squash'
          GITHUB_LOGIN: 'himanshu-tsm'
          ENABLE_GITHUB_API_PREVIEW: false
          ENABLED_FOR_MANUAL_CHANGES: false
          MAXIMUM_RETRIES: 3

      - name: Notify Slack - Approval Required
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "PR #${{ github.event.number }}: Build Passed. Approval Required. <${{ github.event.pull_request.html_url }}|Review and Approve PR>"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  merge:
    runs-on: ubuntu-latest
    needs: approval
    if: github.event.pull_request.merged == false && github.event.action == 'submitted' && success() && github.event.review.state == 'approved'

    steps:
      - name: Merge Pull Request
        run: gh pr merge ${{ github.event.pull_request.number }} --merge

      - name: Notify Slack - PR Merged
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "PR #${{ github.event.number }}: Successfully Merged. <${{ github.event.pull_request.html_url }}|View Merged PR>"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
