name: PR Automation with Docker, Tests, Slack, and Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t sample-nodejs-app .

      - name: Run Tests
        run: docker run --rm sample-nodejs-app npm test

  codeql:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Build the code
        run: npm install

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results/codeql-results.sarif

      - name: Create Results Directory
        run: mkdir -p results

      - name: CheckIfCodeQLOutputExists
        run: ls -R results || echo "No CodeQL results found."

      - name: Upload XML report to Slack
        if: ${{ success() && steps.CheckIfCodeQLOutputExists.outcome == 'success' }}
        run: |
          curl -F file=@results/codeql-results.sarif -F "initial_comment=CodeQL SARIF Report" \
          -F channels=${{ secrets.SLACK_CHANNEL }} \
          -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" https://slack.com/api/files.upload

  approval:
    runs-on: ubuntu-latest
    needs: codeql
    if: ${{ success() }}

    steps:
      - name: Notify Slack - Approval Required
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "PR #${{ github.event.number }}: Build Passed. Approval Required. <${{ github.event.pull_request.html_url }}|Review and Approve PR>"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Wait for Approval (12 hours)
        run: |
          echo "Waiting for approval for 12 hours..."
          sleep 43200  # Sleep for 12 hours (43200 seconds)

      - name: Check Approval Status
        id: approval_check
        env:
          PAT: ${{ secrets.PAT }}  # Use the PAT secret for authentication
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          # Use the GitHub CLI to check the approval status
          REVIEW_STATE=$(gh pr view $PR_NUMBER --json reviews --jq '.reviews | map(select(.author.login == "himanshu-tsm")) | .[0].state' --token $PAT)

          echo "Review State: $REVIEW_STATE"

          if [ "$REVIEW_STATE" == "APPROVED" ]; then
            echo "approved=true" >> $GITHUB_OUTPUT  # Set output variable
          else
            echo "approved=false" >> $GITHUB_OUTPUT  # Set output variable
          fi

  merge:
    runs-on: ubuntu-latest
    needs: approval
    if: ${{ needs.approval.outputs.approved == 'true' }}  # Reference the output here

    steps:
      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT }}  # Set the GitHub token using the PAT secret
        run: gh pr merge ${{ github.event.pull_request.number }} --merge

      - name: Notify Slack - PR Merged
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "PR #${{ github.event.number }}: Successfully Merged. <${{ github.event.pull_request.html_url }}|View Merged PR>"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  timeout:
    runs-on: ubuntu-latest
    needs: approval
    if: ${{ success() }}

    steps:
      - name: Notify Slack - Timeout
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "PR #${{ github.event.number }}: Approval not received within 12 hours. Please review and approve."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
