name: PR Automation

on:
  pull_request:
    branches:
      - main

name: PR Automation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t sample-nodejs-app .

      - name: Run Tests Inside Docker
        run: |
          docker run --rm sample-nodejs-app npm test

      - name: Post Comment on PR
        if: success()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Build and tests passed. Ready for review."

  merge:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Auto Merge PR
        uses: actions-ecosystem/action-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
